### ISSUE TITLE
[Competition Bug]: performance BUG

### ISSUE THREAD

**Issue by ikhsan87** [bitsongofficial/sinfonia-ui#179]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

error when swap btsg to clay[https://drive.google.com/file/d/1Xkmo9gmja4I45D90EFHs5c3ADSOwmgw5/view?usp=sharing](url)

### Describe the issue behavior

error when exchanging btsg to clay [https://drive.google.com/file/d/1Xkmo9gmja4I45D90EFHs5c3ADSOwmgw5/view?usp=sharing](url)

I think this should be fixed quickly for future steps

### BitSong Public Address

bitsong1z92sd3mutvxwfymfue4hwnk72k699n4wcuk5vm

### Osmosis Public Address

osmo1yf3hdg5k0pfj3ml5866c4la6wj03lz2447p8ks

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Hi, as you can read from the error reported in your screenshot, this is a simple error since the high amount of traffic generated a large change in the price (this while you are trying to swap). For this reason, as a protection tool,  you can see your message used a minimum amount value below which you want to decline the transaction.

It is definitively not a bug, it is a security feature.
