### ISSUE TITLE
[Competition Bug]: Slippage Bug

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#183]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Slippage Bug 
1% 3% and manual input bug or always error transaction

Slippage 5% only works

![image](https://user-images.githubusercontent.com/22148449/167455613-bb18239c-d49f-467d-bb44-a12b82d46af8.png)

![image](https://user-images.githubusercontent.com/22148449/167456365-410a11fe-7f1c-413c-8590-3b3ae5618c0d.png)

### Describe the issue behavior

Slippage Bug 

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This is not a bug. As you can see from your screenshot, the value shown right upper the "Slippage Tolerance", i.e., the "**Estimated slippage**" is an ESTIMATE of the slippage value. In a context where a high volume of transactions is executed in a small time, the estimate could not consider those variations. As a consequence, since that value is used to set the minimum amount of token you want to receive (you can access this information from the message you sign with keplr), if this **tolerance** is lower than the one required by the price change, the transaction is automatically declined.

It is definitively not a bug, it is a security feature.
