### ISSUE TITLE
[Bug]: trasfer , swap  

### ISSUE THREAD

**Issue by airmarga** [bitsongofficial/sinfonia-ui#185]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

can't swap with swap many tokens

![image](https://user-images.githubusercontent.com/34205236/167456919-3bd390b7-d1a1-4331-a07b-1ce47c4c551e.png)

### Describe the issue behavior

error if swap many token 

![image](https://user-images.githubusercontent.com/34205236/167457424-48e9c15e-daa5-405c-89db-2a057816da01.png)

### BitSong Public Address

bitsong1vjq2cruphkke0tm6nz9qk7t240260j44l8ws6j

### Osmosis Public Address

osmo1vjq2cruphkke0tm6nz9qk7t240260j44m40gw0

### Which browser are you using?

Google Chrome

### Which is your browser version?

Versi 101.0.4951.54 (Build Resmi) (64 bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

**Comment by Giorgionocera** [comment]
This is not a bug. As you can see from your screenshot, the "Estimated slippage" is an ESTIMATE of the slippage value. In a context where a high volume of transactions is executed in a small time, the estimate could not consider those variations. As a consequence, since that value is used to set the minimum amount of token you want to receive (you can access this information from the message you sign with keplr) if this tolerance is lower than the one required by the price change, the transaction is automatically declined.

It is definitively not a bug, it is a security feature.
