### ISSUE TITLE
[Competition Bug]: Transaction failed and UI bug

### ISSUE THREAD

**Issue by shallbe** [bitsongofficial/sinfonia-ui#202]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

1 Problem: When in the Swap tab, at the top right in the fan tokens table, I select some user token and then click swap on the token page, then I get thrown to swap to an Adam Clay token every time. And so with all the tokens
2 problem: When I set a certain slippage and then for example switch to another tab, the slippage value is reset to the default value
3 problem: When you write an amount, for example in the swap, in the amount input window there is always a digit 0 and if you start writing a number, the digit zero stays in front of it
4 problem: When adding tokens to pools of liquidity, the same pool is displayed both at the top (my pools) and at the bottom (all pools) - it makes no sense, I suggest you remove from all pools those pools in which the user has already added liquidity
5 problem:
![1](https://user-images.githubusercontent.com/85305483/167475889-d038629b-4b26-47b0-8191-d714b2bc943c.PNG)
 

### Describe the issue behavior

It's all described above, sorry if I made it inconvenient for you

### BitSong Public Address

bitsong1t9n3uzfwtknhk88gvtxrfq08jna8jpq0c0sxaw

### Osmosis Public Address

osmo1af4yrw9yz42rum7tpnwmuff4cuqt3qxv77c9gr

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This issue is composed of numerous "problems".
It is better to create a new issue for each problem and **to check if there exist the same issues** as you confirmed by checking: "You checked that the problem has not yet been reported (also through closed issues)."

In any case, I'll answer you by points:
1. Duplicated of #178
2. It is not a bug. It is a wanted behavior.
3. It is not a bug.
4. On top there are "your pools". Only yours, which makes it easier to reach them and perform operations on them.
5. You did not provide any information on when that transaction failed. What were you doing?

So, this is invalid and no one of the reported issues is a bug.
