### ISSUE TITLE
Move start earning button

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#394]
Andrea is proposing to move the "start earning" button near to the "Add/Remove Liquidity" one.
This could help the user to understand the result of the operation to the user and that he needs to complete the operation.

Please @giannnni, can we have feedback on this?

**Comment by giannnni** [comment]
In my idea "Start Earning" button can't go above Liquidity Mining section because it's strictly related to this area. 

Few steps back, to provide liquidity inside our pools Sinfonia User has to perform two actions, first of all he needs to put his money inside and then he bonds it. So there are two consecutive actions and you could find them clearly separated one below the other at the top of the Pool Detail Page. 
Changing position of Start Earning button will reduce the quality of information about different bonding periods and collapsing Liquidity Mining section is the real consequence at that point of moving button outside the area that contains only infos about the "start earning" action and nothing more. 

So in my opinion moving "Start Earning" button means to remove all the liquidity mining section too, with every info about APR related to bonding periods, incentives and epoch time cause maintaining it in that position would be useless due to relation between CTA and section infos.

**Comment by Giorgionocera** [comment]
I got your point and it makes sense. What about adding some "hint" for the user? Like something to say: "ok, now let's bond this money you put in the pool!".
Could this help in your opinion? @giannnni

**Comment by giannnni** [comment]
No, it would be useless at this time. Our total audience came from Osmosis so they know perfectly as using the platform. In other way I know that we need to rethink the whole process for users that doesn't know what's a pool and how it works.

So let me know if you want to redesign it from the start or not.

**Comment by Giorgionocera** [comment]
If you think it could be useful to redesign the process to help also new users, please let's start this work. 💪
